### ISSUE TITLE
error  Parsing error: Unexpected token as

### ISSUE THREAD

**Issue by huccct** [ota-meshi/astro-eslint-parser#243]
Excuse me, I was wondering why I get the following error in pnpm lint in husky after I configured astro-eslint-parser
![image](https://github.com/ota-meshi/astro-eslint-parser/assets/87902123/76e5838e-eaf0-4a50-81a3-015a1ce83611)
And this is my .eslintrc.cjs, so i don't know why 
![image](https://github.com/ota-meshi/astro-eslint-parser/assets/87902123/5042edcf-e343-4ce3-a413-096fa2b0a652)
I used it in my file like this
![image](https://github.com/ota-meshi/astro-eslint-parser/assets/87902123/85f7c434-b3a6-4f4e-a8d8-5050270b7869)

**Comment by ota-meshi** [comment]
I am closing the issue because the required information is not provided.
