### ISSUE TITLE
typescript-eslint crashes when I use set:html on Astro Fragment

### ISSUE THREAD

**Issue by arty-name** [ota-meshi/astro-eslint-parser#256]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I'm using [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro). (`*.astro` file linting does not work with the parser alone. You should also use eslint-plugin-astro with it.)
- [X] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) repo and open the issue in [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) repo if there is no solution.
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.53.0

### What version of `eslint-plugin-astro` and `astro-eslint-parser` are you using?

- astro-eslint-parser@0.16.0
- eslint-plugin-astro@0.29.1

### What did you do?

<details>
<summary>Configuration</summary>

```json
{
  "extends": [
    "standard-with-typescript",
    "plugin:@typescript-eslint/strict-type-checked"
  ],
  "plugins": ["astro"],
  "overrides": [
    {
      "files": ["*.astro"],
      "parser": "astro-eslint-parser",
      "parserOptions": {
        "parser": "@typescript-eslint/parser",
        "extraFileExtensions": [".astro"]
      }
    }
  ]
}

```
</details>

```astro
---

---

<div>
  <Fragment set:html={'content'} />
</div>

```

### What did you expect to happen?

I expect the linter to complete linting the file

### What actually happened?

Linter crashes with this error:

```
Oops! Something went wrong! :(

ESLint: 8.51.0

TypeError: Cannot read properties of undefined (reading 'parent')
Occurred while linting src/pages/index.astro:6
Rule: "@typescript-eslint/no-unsafe-assignment"
    at Object.getContextualType (node_modules/@typescript-eslint/type-utils/dist/getContextualType.js:34:25)
    at checkAssignment (node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment.js:182:24)
    at JSXAttribute[value != null] (node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment.js:279:17)
    at ruleErrorHandler (node_modules/eslint/lib/linter/linter.js:1091:28)
    at node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

### Link to Minimal Reproducible Example

https://github.com/arty-name/typescript-eslint-astro-fragment

### Additional comments

I don’t have the expertise to decide which of the integrated components should be adjusted, and rely on your judgement. I have initially [reported this issue to typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/issues/7886) and they think the cause is the astro-eslint-parser.

**Comment by ota-meshi** [comment]
Thank you for posting this issue!

It seems that the bug is caused by generating a new node and making it impossible to identify the type information. I think we need to overwrite the original node instead of generating a new node.

https://github.com/ota-meshi/astro-eslint-parser/blob/858d0a9d45bc6fa2896ba6f6ad31dbf49cc3f942/src/parser/process-template.ts#L469

**Comment by erikschul** [comment]
I'm experiencing this as well.

**Comment by erikschul** [comment]
Although it seems that Astro in general requires disabling a few lints:
https://raw.githubusercontent.com/Princesseuh/erika.florist/main/.eslintrc.cjs

```
// All the rules below are disabled because they're cumbersome to fix. Would be great to one day though
		"@typescript-eslint/no-unsafe-return": "off",
		"@typescript-eslint/no-unsafe-assignment": "off",
		"@typescript-eslint/no-misused-promises": [
			"error",
			{
				checksVoidReturn: false,
			},
		],
		"@typescript-eslint/no-unsafe-member-access": "off",
		"@typescript-eslint/no-unsafe-call": "off",
```

**Comment by arty-name** [comment]
Thank you Yosuke Ota!
