### ISSUE TITLE
Extract style blocks as virtual css files

### ISSUE THREAD

**Issue by tinchoz49** [ota-meshi/astro-eslint-parser#268]
### Description

Hey @ota-meshi, how are you?

I'm working with the [antfu/eslint-config](https://github.com/antfu/eslint-config) and now it support lint/format css files. I notice that it also works with `vue` templates so I try to understand into how it works and I found that the vue js parser takes the <style> blocks and convert to virtual files so eslint can format it by the `.css` extension.

Do you think that this could be a good feature for astro-eslint-parser?

This is the module: https://github.com/antfu/eslint-processor-vue-blocks

My current configuration for astro + eslint:

```js
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import antfu from '@antfu/eslint-config'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const compat = new FlatCompat({
  baseDirectory: __dirname,
  resolvePluginsRelativeTo: __dirname,
})

/** @type {import('eslint').Linter.FlatConfig[]} */
export default antfu(
  {
    formatters: {
      css: true,
      html: true,
      markdown: true,
    },
  },
  ...compat.config({
    overrides: [{
      files: ['**/*.astro'],
      extends: [
        'plugin:astro/recommended',
        'plugin:astro/jsx-a11y-recommended',
      ],
      globals: {
        astroHTML: true,
      },
      env: {
        // Enables global variables available in Astro components.
        'node': true,
        'astro/astro': true,
        'es2020': true,
      },
      parser: 'astro-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        extraFileExtensions: ['.astro'],
      },
      rules: {
        // this is necessary to force a correct indentation in astro
        'style/indent': ['error', 2],
        'style/jsx-indent': 'off',
        'style/jsx-one-expression-per-line': 'off',
      },
    }],
  }),
)
```

**Comment by ota-meshi** [comment]
I think we can use astro-eslint-parser to do something similar to eslint-processor-vue-blocks.

I'm already using it to extract script tags with eslint-plugin-astro.
https://github.com/ota-meshi/eslint-plugin-astro/blob/37dfdbb6079f891be1e7fed9554a388320370893/src/processor/index.ts#L8

However, I think it needs to be a separate module from the parser like eslint-processor-vue-blocks.
