### ISSUE TITLE
Parsing error occured when reference charactors are in attribute.

### ISSUE THREAD

**Issue by masuP9** [ota-meshi/astro-eslint-parser#275]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [ ] I'm using [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro). (`*.astro` file linting does not work with the parser alone. You should also use eslint-plugin-astro with it.)
- [X] I'm sure the problem is a parser problem. (If you are not sure, search for the issue in [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) repo and open the issue in [eslint-plugin-astro](https://github.com/ota-meshi/eslint-plugin-astro) repo if there is no solution.
- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

I have not used it. It happened when using @markuplint/astro-parser which depends on astro-eslint-parser.

### What version of `eslint-plugin-astro` and `astro-eslint-parser` are you using?

- astro-eslint-parser@0.16.0

### What did you do?

<details>
<summary>Configuration</summary>

```
// default
```
</details>

```astro
---

---

<a href="https://example.com/hoge.html?args=&amp;id=buttons">
	Button Story
</a>
```

### What did you expect to happen?

No parse error.

### What actually happened?

[5:8]: Parsing error: Unknown token at 18, expected: ["\"https://example.com/hoge.html?args=&id=buttons\"","'https://example.com/hoge.html?args=&id=buttons'","https://example.com/hoge.html?args=&id=buttons"], actual: "\"https://e" ([null ](https://ota-meshi.github.io/astro-eslint-parser/playground/))

### Link to Minimal Reproducible Example

https://ota-meshi.github.io/astro-eslint-parser/playground/#eJyrVkrOT0lVslLS1dWNyYvJg1I2iQoZRalptjFKGSUlBcVW+vqpFYm5BTmpesn5ufoZ+empehkluTn2iUXpxbZqQBnrzBTbpNKSkvy84hglO6ARJU5gnkJwSX5RJdBA/USQaJ5SLQCkYife

### Additional comments

英語で分かりにくいところがあればすみません！

**Comment by ota-meshi** [comment]
Thank you for posting the issue. I will fix the bug.
