### ISSUE TITLE
Bump typescript-eslint support range to include 6 and 7?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ota-meshi/astro-eslint-parser#313]
https://github.com/ota-meshi/astro-eslint-parser/blob/2057ca0998681d1b5930c2bbb7b53c1b42fd6cea/package.json#L52-L54

We've since released major versions 6 and 7 of typescript-eslint. Would you accept a PR that adds `|| ^6.0.0 || ^7.0.0` to those ranges? It seems to work in local testing for me.

Allowing this to reuse consumer's newer typescript-eslint versions would be a nice change for a few reasons:

* The v5 packages are generally out-of-date and don't support all the latest TypeScript syntax
* Older v5 versions still have a dependency on [`tsutils`](https://npmjs.com/package/tsutils), which is also out-of-date, instead of its successor [`ts-api-utils`](https://www.npmjs.com/package/ts-api-utils)

**Comment by ota-meshi** [comment]
Thanks for the suggestion.
I would like to drop support for older node versions and upgrade those packages to v7.
If you open that PR I'll accept it.
