### ISSUE TITLE
Support typescript-eslint@8?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ota-meshi/astro-eslint-parser#332]
👋 Coming over from https://github.com/ota-meshi/eslint-plugin-astro/issues/411, this package only allows `typescript-eslint` packages on version 7:

https://github.com/ota-meshi/astro-eslint-parser/blob/6c343c9cd64e57ff73681e3f3d6383fb6c6d4413/package.json#L52-L54

Would you be up for a PR adding on typescript-eslint@8 support?

**Comment by JoshuaKGoldberg** [comment]
Ping @ota-meshi - is there anything I can do to help here? Would you accept a PR?

**Comment by ota-meshi** [comment]
I've been busy these past few months and I'm currently overwhelmed with a lot of missed notifications 😓 
If you could send a PR that would be much appreciated.
