### ISSUE TITLE
Issues parsing return JSX inside loops

### ISSUE THREAD

**Issue by killpowa** [ota-meshi/astro-eslint-parser#48]
I am having troubles auto formatting/validating this astro page

```
---
import i18next from "i18next";
import ISO6991 from "iso-639-1";
import { localizePath } from "astro-i18next";

interface Props {
  showFlag?: boolean;
}

const supportedLanguages = i18next.languages;
const currentLanguage = i18next.language;

const { pathname } = Astro.canonicalURL;

const { showFlag = false, ...attributes } = Astro.props;
---

<select onchange="location = this.value;" {...attributes}>
  {supportedLanguages.map((supportedLanguage: string) => {
    let value = localizePath(pathname, supportedLanguage);
    const nativeName = ISO6991.getNativeName(supportedLanguage);

    return  (<option value={value} selected={supportedLanguage === currentLanguage}>
        {nativeName}
      </option>);
  })}
</select>

```
The issue seems to be the 
```
    return  (<option value={value} selected={supportedLanguage === currentLanguage}>
        {nativeName}
      </option>);
```
part. If you replace the JSX after the return with any typescript primitive value like `123`, the formatting and validation work.

**Comment by ota-meshi** [comment]
I can't reproduce your problem. Please provide a minimal repository to reproduce the problem.

https://ota-meshi.github.io/astro-eslint-parser/playground/#eJxtkl9rgzAUxb/KxSeFaimDsrbGsZfBoHRjY2++pOmtCjGRJHZj4ndfNEv/zPmiXs+993dO7AImDxisgziOc1HVjVQGqsW9wC8DRyVryIPf1zzYnBXP7y/L1WpxVmgZL+9W8eJa0wGXjPLqG1+pKaH3YqqNkvH1UNsiDKojZQivSjYaulwA6FJ+PnFaPKxhLyVHKqy2H+RMCm1At82wCA9bKoqWFqiBePaE+9rGy1mrFArjxf9oN5fZHTQWWtAaLTiBx4E5YVRIUVlPH2/bG60ntcoj5RpnkCQJNUZV+9ZYrMuIZrBne8e4c5Fq5MgMSMFKC4EkD4bQTCWFbTFlpZMT5a0lC6C7mdlnQ0TdNIOkpk0YTuprsPsrUURAMhcvAEcD43i76/qsQu99Ns042rheZ11Y1BPuhpiI/ymSAs3uXJ+SRGN0wwyFplX2KUxlM1oeYUg33npw2eCBTF0CIeTvgbpE3NVdwHpfTeduS+Ys9JH9ks7dkizofwBYThJ0
