### ISSUE TITLE
Issues with typescript in front matter

### ISSUE THREAD

**Issue by nrgnrg** [ota-meshi/astro-eslint-parser#51]
Heya,

Just added this to an Astro SSR with typescript project and generally it works great! thank you for your work on it.

I've encountered a few issues with using this on an Astro SSR/typescript project with the code in the front matter so thought I would report what I was seeing.

- `'Astro' is not defined.` eslint([no-undef](https://eslint.org/docs/rules/no-undef)) - somewhat understandably eslint is unaware of the Astro global, oddly typescript seems fine with it but I'm not sure if thats because of the Astro extension in vscode I'm using.
- The parser seems to struggle with various issues related to `eslint-plugin-prettier`, I imagine this is potentially related to the conversion to `.tsx`, in my limited usage I saw:
  - `Parsing error: 'import' can only be used in 'import()' or 'import.meta'.` eslint([prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)) - this occurs on an import which only has side effects `import "package";`
  - Issues with white space don't seem to get picked up
  - Various random `Parsing error: Unexpected token, expected "" eslint`([prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options)) errors
-  I also see `Parse errors in imported module: parser.parse is not a function (undefined:undefined)` eslint([import/namespace](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/namespace.md)), the same import is not an issue in other files

**Comment by ota-meshi** [comment]
The parser does not process variables. You can use the `env` provided by eslint-plugin-astro to solve the problem.
https://github.com/ota-meshi/eslint-plugin-astro

Other issues, I don't think it's an astro-eslint-parser issue.
If you would like to help solve the problem, please share the minimum repository that reproduces the problem.

**Comment by AslamPangestu** [comment]
Hey, i have similar problem. can you check it?below is the repo

https://github.com/AslamPangestu/aslampangestu-blog
